CREATE TABLE `parcelAgents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`companyName` varchar(200),
	`city` varchar(100) NOT NULL,
	`username` varchar(50) NOT NULL,
	`passwordHash` varchar(255) NOT NULL,
	`coveredCities` text,
	`pickupTime` varchar(20),
	`pickupDays` varchar(100),
	`pricingJson` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`logoUrl` text,
	`notes` text,
	`totalParcels` int NOT NULL DEFAULT 0,
	`totalDelivered` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `parcelAgents_id` PRIMARY KEY(`id`),
	CONSTRAINT `parcelAgents_phone_unique` UNIQUE(`phone`),
	CONSTRAINT `parcelAgents_username_unique` UNIQUE(`username`)
);
--> statement-breakpoint
CREATE TABLE `parcelStatusLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`parcelId` int NOT NULL,
	`status` varchar(50) NOT NULL,
	`note` varchar(300),
	`updatedBy` enum('system','driver','agent','admin') NOT NULL DEFAULT 'system',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `parcelStatusLogs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `parcels` (
	`id` int AUTO_INCREMENT NOT NULL,
	`trackingNumber` varchar(20) NOT NULL,
	`deliveryType` enum('instant','scheduled','intercity') NOT NULL,
	`senderId` int NOT NULL,
	`senderName` varchar(100),
	`senderPhone` varchar(20),
	`recipientName` varchar(100) NOT NULL,
	`recipientPhone` varchar(20) NOT NULL,
	`pickupAddress` varchar(500) NOT NULL,
	`pickupLat` decimal(10,7),
	`pickupLng` decimal(10,7),
	`dropoffAddress` varchar(500) NOT NULL,
	`dropoffLat` decimal(10,7),
	`dropoffLng` decimal(10,7),
	`fromCity` varchar(100),
	`toCity` varchar(100),
	`parcelSize` enum('small','medium','large') NOT NULL DEFAULT 'small',
	`parcelDescription` varchar(300),
	`parcelPhotoUrl` text,
	`estimatedWeight` varchar(50),
	`price` decimal(10,2),
	`paymentMethod` enum('cash') NOT NULL DEFAULT 'cash',
	`scheduledDate` varchar(20),
	`scheduledTimeSlot` varchar(50),
	`driverId` int,
	`agentId` int,
	`status` enum('pending','accepted','picked_up','in_transit','delivered','cancelled','returned') NOT NULL DEFAULT 'pending',
	`cancelReason` varchar(300),
	`deliveryOtp` varchar(6),
	`deliveryOtpVerified` boolean NOT NULL DEFAULT false,
	`acceptedAt` timestamp,
	`pickedUpAt` timestamp,
	`deliveredAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `parcels_id` PRIMARY KEY(`id`),
	CONSTRAINT `parcels_trackingNumber_unique` UNIQUE(`trackingNumber`)
);
